// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GenericStore.Domain.Entities;

namespace GenericStore.Domain.Entities;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal Total { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}