// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GenericStore.Domain.Entities;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public bool OnSale { get; set; }

    public int? CategoryId { get; set; }

    public DateTime CreatedDate { get; set; }
    
    public virtual Category? Category { get; set; }

    public virtual OrderDetail? OrderDetail { get; set; }

    public virtual StoreProduct? StoreProduct { get; set; }
}