// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GenericStore.Domain.Entities;

public partial class Store
{
    public int StoreId { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public virtual IEnumerable<StoreProduct> StoreProducts { get; set; }
}