// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using GenericStore.Domain.Entities;
using System;
using System.Collections.Generic;

namespace GenericStore.Domain.Entities;

public partial class StoreProduct
{
    public int StoreProductId { get; set; }

    public int StoreId { get; set; }

    public int ProductId { get; set; }

    public int Stock { get; set; }

    public int MinimumStock { get; set; }

    public virtual Store Store { get; set; }

    public virtual Product Product { get; set; }
}