// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.Application.DTOs;
using GenericStore.Application.DTOs;

namespace GenericStore.Domain.Entities;

public partial class ProductDTO : BaseEntityDTO
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public bool OnSale { get; set; }

    public int? CategoryId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual StoreProductDTO StoreProduct { get; set; }
}